In [1]:
import pandas as pd

In [8]:
comment = pd.read_csv("./OUTPUT-1/Comment.csv")

In [9]:
comment

,RevId,UserId,ResId,Comment,image_urls,Food_score_cmt,Services_score_cmt,Atmosphere_score_cmt,Position_score_cmt,Price_score_cmt
0,1942111,372656,200790,"Quán nằm trên đường Trung Hòa, dễ tìm, nhân vi...",https://images.foody.vn/res/g21/200790/s800/fo...,9,8,9,8,8
1,2156575,1564023,200790,Vì nhà mình tổ chức tiệc có 11 người nên là tr...,https://images.foody.vn/res/g21/200790/s800/fo...,9,9,8,8,6
2,2655734,12260513,200790,Mình đặt chả cá Anh Vũ Trung Hoà lần đầu vì th...,https://images.foody.vn/res/g21/200790/s800/fo...,10,10,10,10,10
3,2233082,8296274,200790,✔️ Vị trí\nMặt đường Trung Hoà nên khá dễ tìm\...,https://images.foody.vn/res/g21/200790/s800/fo...,8,7,7,8,8
4,1158517,1783611,200790,"Thích ăn chả cá ở đây, thịt ướp vừa vặn cá giò...",https://images.foody.vn/res/g21/200790/s800/fo...,8,8,7,8,8
...,...,...,...,...,...,...,...,...,...,...
3130,3307802,17533802,966973,Lần đầu tiêu riview quán vì thất vọng rất nhiề...,https://images.foody.vn/res/g97/966973/s800/fo...,3,2,2,5,5
3131,3854659,18762268,966973,Là một khách tủ mỗi tuần đóng họ 1 lần nên bài...,https://images.foody.vn/res/g97/966973/s800/fo...,10,10,8,10,10
3132,371978,910285,100842,Công ty tớ gần đây nhân ngày trời mưa rủ nhau ...,https://images.foody.vn/res/g11/100842/s800/fo...,9,8,7,10,7
3133,541381,395412,100842,"Công ty mình tổ chức ăn tất niên tại đây, quán...",https://images.foody.vn/res/g11/100842/s800/fo...,8,7,7,7,6
3134,879089,1726428,100842,Mình biết quán này lâu rồi nhưng hqua mới có d...,https://images.foody.vn/res/g11/100842/s800/fo...,8,8,8,8,6

In [16]:
user = pd.read_csv("./OUTPUT-1/User.csv")

In [17]:
user1 = user.drop_duplicates(subset=['UserId'])

In [18]:
user1

        UserId  Total_reviews  Followers
0       372656            450        251
1      1564023             43         56
2     12260513              3          0
3      8296274             30          3
4      1783611             37        201
...        ...            ...        ...
3130  17533802              1          0
3131  18762268              1          0
3132    910285              9          1
3133    395412            175         16
3134   1726428             15          1

[3135 rows x 3 columns]

In [19]:
restaurant = pd.read_csv("./OUTPUT-1/Restaurant.csv")

In [20]:
restaurant = restaurant.drop_duplicates(subset=['ResId'])

In [21]:
restaurant

,ResId,Rating,streetAddress,district,region,Res_pos_score,Res_price_score,Res_food_score,Res_atmosphere_score,Res_services_score
0,200790,8.4,103 Trung Hoà,Quận Cầu Giấy,Hà Nội,8.3,8.2,7.9,7.5,7.5
5,44727,6.2,Trần Vĩ,Quận Cầu Giấy,Hà Nội,7.1,6.7,6.5,6.4,6.1
6,995584,7.4,163 Tô Hiệu,Quận Cầu Giấy,Hà Nội,4.5,4.5,4.5,4.0,3.5
7,109338,7.2,66 Duy Tân,Quận Cầu Giấy,Hà Nội,7.1,6.7,6.6,5.9,5.7
9,221742,1.0,"C03 Ngõ 69 Dương Khuê, P. Mai Dịch",Quận Cầu Giấy,Hà Nội,1.6,1.6,1.6,1.6,1.6
...,...,...,...,...,...,...,...,...,...,...
3124,714755,7.4,37 Trung Hòa,Quận Cầu Giấy,Hà Nội,7.0,6.6,6.3,6.1,5.4
3125,201735,4.8,167 Nguyễn Ngọc Vũ,Quận Cầu Giấy,Hà Nội,6.8,6.5,6.0,5.8,5.5
3127,689038,9.6,"Tầng 4-1, Tòa V4, Home City, 177 Trung Kinh",Quận Cầu Giấy,Hà Nội,9.0,8.7,8.3,8.2,7.5
3129,966973,8.4,6b Ngõ 92 Nguyễn Khánh Toàn,Quận Cầu Giấy,Hà Nội,6.8,6.8,6.7,6.6,6.2
3132,100842,8.2,39 Trần Kim Xuyến,Quận Cầu Giấy,Hà Nội,7.9,7.8,7.4,6.9,6.5